### ISSUE TITLE
Add native adreno 200 (Mesa freedreno) support?

### ISSUE THREAD

**Issue by lorn10** [Halamix2/linux-next-qcom-msm7227a#1]
Hi there Halamix2

With some delay, a happy new year also to you. :-)

Here follows a technical question. This kernel is version 4.19 based, right? If so, would it be possible to add native freedreno (Mesa) support regarding the Adreno 200 GPU? That one was implemented in kernel version 4.20 and should be also compliant to kernel 4.19. (I have asked the original code developer and the chance seems good.) It is confirmed that the freedreno open source drivers outperform the proprietary blobs in many aspects.

I got the following git command:

git cherry-pick 21af872cd8c695060dd1d045293bf21ea9156a51

Because I am a very beginner regarding the use of git I place it here. Maybe it will be helpful also in this project. However, I have no idea how big the effort of implementing native Mesa freedreno driver support for the galaxy mini 2 really is.

Kind regards from the alps
lorn10

**Comment by Halamix2** [comment]
I'm sorry, but I'm not working on this port anymore.
When I started I was a bit too optimistic, but now I know the fact that the kernel has version 4.19 is not enough, it would also need to be mainlined, or simply be on par with kernel.org.
This is a job is simply too hard for me, as it would require great amount of work and knowledge (rewriting all board.h files into C drivers and device tree files, having working UART or output of sorts etc.)
